### ISSUE TITLE
V2.4.0_NRK_RC2 - Channel Route and Layer Route commands do not route audio. Channel delay not active.

### ISSUE THREAD

**Issue by amwtech** [nrkno/sofie-casparcg-server#60]
### Expected behaviour
When a clip with audio is played in a channel, and that channel is routed to a second channel the video and audio should route to the destination channel.

When a delay is specified (FRAMES_DELAY 10) the routed signal should be delayed by the number of frames specified (within sensible delay values).

These are the behaviours seen in server 2.1.12_NRK.

### Current behaviour
Video is routed, audio is not routed. The delay is ignored.

----

### Steps to reproduce
1. Play a clip in a channel
2. Add a route channel or a route layer to a second channel
3. Observe the output of the route destination channel. No routed audio, no delayed video/audio.

### Environment
* Server version: v2.4.0-NRK-RC2
* Operating system: Windows 10

**Comment by Julusian** [comment]
The audio is fixed in master, but it has not been tagged yet. I don't think we have builds of that available.
It is also fixed in the builds upstream.

It looks like support for the delay got dropped upstream in 2.2. It would be better to open an issue about it there https://github.com/casparcg/server, as nrkno is unlikely to reimplement it, but if it is re-implemented upstream it will make its way into these versions too

**Comment by Julusian** [comment]
The route audio was fixed in https://github.com/nrkno/sofie-casparcg-server/releases/tag/v2.4.0-NRK-RC3
